[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages=['facet_ml']

[metadata]
name = 'facet_ml'
version = '0.1.0'

[project]
name = 'facet_ml'
version = '0.1.0'